baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'papermod'

[params]
# Other params go here...

[[params.socialIcons]]
name = "github"
url = "https://github.com"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com"
