baseURL = "https://sharadv.xyz/"
languageCode = "en-us"
title = "CAKE FOR BREAKFAST"
theme = "cake"

# Enable useful features
enableRobotsTXT = true
enableGitInfo = true

[params]
description = "A blog by Sharad Venkat"
twitter = "sharadv"

# Taxonomies
[taxonomies]
tag = "tags"

# Output formats
[outputs]
home = ["HTML", "RSS"]

# RSS settings
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "index"
