baseURL = 'https://sharadv.netlify.app/'
languageCode = 'en-us'
title = 'Sharad Venkat'
theme = 'terminal'
[languages.en.params.logo]
logoText = "Sharad Venkat"
logoHomeLink = "/"
[params]
ReadMore = "Read More"
readingTime = true
