baseURL = 'https://sharadv.netlify.app/'
languageCode = 'en-us'
title = 'Sharad Venkat'
theme = 'terminal'
[languages.en.params.logo]
logoText = "Sharad Venkat"
logoHomeLink = "/"
[params]
ReadMore = "Read More"
readingTime = true

[menu]
[[menu.main]]
name = "archive"
url = "archives"
weight = 5

[[menu.main]]
name = "about"
url = "about/"
weight = 10

[[menu.main]]
name = "tags"
url = "tags/"
weight = 10
