baseURL = 'https://sharadv.xyz/'
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
title = 'Sharad Venkat'
theme = 're-terminal'
[languages.en.params.logo]
logoText = "Sharad Venkat"
logoHomeLink = "/"
[params]
ReadMore = "Keep reading"
readingTime = true
centerTheme = true
themeColor = "orange"

[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = "sharad"
site = "x.com/sharadv"

[menu]
[[menu.main]]
name = "archives"
url = "/archives/"
weight = 5

[[menu.main]]
name = "lists"
url = "/lists/"
weight = 5

[[menu.main]]
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
name = "tags"
url = "/tags/"
weight = 10
