name = "Cake"
license = "MIT"
licenselink = "https://github.com/sharadv1/hugoblog/blob/main/LICENSE"
description = "A minimal, single-page blog theme with expandable posts"
homepage = "https://sharadv.xyz"
min_version = "0.90.0"

[author]
  name = "Sharad Venkat"
